services:
  api:
    build: .
    restart: always
    network_mode: "host"
    environment:
      SCPBATTLES_STEAM_API_KEY: ${SCPBATTLES_STEAM_API_KEY}
      SCPBATTLES_MONGODB_ADDDRESS: mongodb
      SCPBATTLES_OFFICIAL_SERVER_TOKEN: ${SCPBATTLES_OFFICIAL_SERVER_TOKEN}
  
  mongodb:
    image: mongo:7.0.0-rc8-jammy
    restart: always
    network_mode: "host"
    volumes:
      - ${SCPBATTLES_MONGODB_PATH}:/data/db
    