services:
  mongodb:
    image: mongo:7.0.0-rc8-jammy
    restart: always
    network_mode: "host"
    volumes:
      - mongodb-data:/data/db
  
  api:
    build: .
    restart: always
    network_mode: "host"
    environment:
      SCPBATTLES_STEAM_API_KEY: ${SCPBATTLES_STEAM_API_KEY}
      SCPBATTLES_MONGODB_ADDDRESS: mongodb
      SCPBATTLES_OFFICIAL_SERVER_TOKEN: ${SCPBATTLES_OFFICIAL_SERVER_TOKEN}

    depends_on:
      - mongodb

volumes:
  mongodb-data:
    