services:
  api:
    image: scpbattlesapi:latest
    ports:
      - 5000:5000
    environment:
      SCPBATTLES_STEAM_API_KEY: E6A4346C76567A0152BEF44454E24BAA
      SCPBATTLES_MONGODB_ADDDRESS: "192.168.0.127"
      SCPBATTLES_OFFICIAL_SERVER_TOKEN: XmrUrnMpOOSXQPRXRyStpDANnfEPQRY
  

  mongodb:
    image: mongo:7.0.0-rc8-jammy
    ports:
      - 27017:27017
    volumes:
      - /mnt/enderchest/mongodb:/data/db
    