case_key_map:
  51:
  - 52
  67:
  - 52
case_probabilities:
  51:
    5999:
    - 43
    - 46
    - 49
    - 58
    8499:
    - 47
    - 42
    - 53
    9499:
    - 48
    - 50
    - 55
    9899:
    - 45
    - 44
    - 34
    10000:
    - 54
  67:
    5999:
      - 62
      - 74
      - 75
      - 76
      - 79
    8499:
      - 65
      - 66
      - 73
      - 78
    9499:
      - 64
      - 70
      - 71
    9899:
      - 61
      - 81
    10000:
      - 69

bonus_item_probabilities:
  5999: # 60 percent
    []
  8499: # 25 percent
    - 68
    - 80
  9499: # 10 percent
    []
  9899: # 4 percent
    []
  1000: # 1 percent
    []

crafting_recipes:
  27:
  - 27
  - 25
default_items:
- 2
- 3
- 4
- 5
- 6
- 7
- 39
- 41
- 40
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
